### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by smorello87**
Added the links to the Omeka.net installation guide

### CODE REVIEW

**Comment by kallewesterling** [comment]
Hi @smorello87 - I believe this is for the January DRI? This curriculum (where you're suggesting the edit) is for the DHRI (the NEH-funded project that I'm coordinating). I think you can check with @smythp about where this edit should go (but I don't think it's into this repository).

**Comment by smorello87** [comment]
Thank you, Kalle! I believe this is the page that's going to be linked in
the letters that are going out for the January DRI. The instructions to the
Omeka workshop have been moved and now live on the DF GitHub account, but I
think it needs to be linked here anyway, since this is going out to all DRI
2019 participants.

**Comment by kallewesterling** [comment]
Maybe @smythp can provide some clarification here but I don't think this is where the January DRI participants will go? This page is set up for the DHRI participants (dhinstitutes.org). I believe that this is the install directions for the DRI: https://github.com/GCDigitalFellows/installdri.github.io. I'll leave it here for @smythp to follow up as I am not sure about any of this (I haven't been to any of your meetings!)

**Comment by smythp** [comment]
I think that the idea was that this one was the most up-to-date and so would be used for the email. Perhaps confirmation from @lmrhody on this?

**Comment by kallewesterling** [comment]
I see. As I told @lmrhody: To me, it would make more sense to edit the installdri.github.io fork (https://github.com/GCDigitalFellows/installdri.github.io), and then let those edits propagate down through the structure, rather than in the DHRI one. But I'm happy to follow along with any decisions you guys make! Just want to make sure we have all of the different repos in order.

**Comment by smythp** [comment]
Rafael, would using the version in the Fellows account mean you'd have to redo a bunch of work? We could use what you've done here and push it to the Fellows account as an option. It does seem like what Kalle says makes sense, but not sure if it'll set you back or not.

**Pull request merged**
