### PR TITLE
Proposed revision of README

### PR DESCRIPTION
**Pull request by kallewesterling**
Here's a proposed revision of README that adheres to the style guide for the DHRI curriculum, contains the proper credits and acknowledgements, as well as cleans up somewhat in both lines in the text and the `sections` directory. Addresses #1.

### CODE REVIEW

**Review by story645 — COMMENTED** [review]
ost the link to the Python installs

**Comment by kallewesterling** [comment]
I'm not sure what this comment means @story645, can you clarify?

**Comment by smythp** [comment]
Hi Kalle,

This looks great, I made a few small edits and was going to create a PR to update your PR, but thought that would be annoyingly complicated, so merged my small changes and then updated master. Thanks for making this look nice.

**Comment by kallewesterling** [comment]
Awesome. Thanks!

**Pull request merged**
